import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactElement } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Main",
  description: "Generated by create next app",
};

type Props = {
  children: ReactElement;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <head />
      {children}
    </html>
  );
}
