import { Button } from "@/components/ui/button";
import Link from "next/link";
import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Error 404",
  description: "Generated by create next app",
};

const NotFound = () => {
  return (
    <div>
      <main className="text-red-400 min-h-screen min-w-screen flex justify-center items-center">
        <div>
          <h1 aria-label="404 Not Found">404</h1>
          <p>Page Not found!</p>
          <Link href="/">
            <Button>Back to safety!</Button>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default NotFound;
