import { Metadata } from 'next';
import React from 'react'
import Image from 'next/image'
import front_img from '@/assets/front_img.png'
import { Button } from '@/components/ui/button';
import { Lightbulb } from "lucide-react";
import Link from 'next/link';
import { useRouter } from 'next/router';
export const metadata: Metadata = {
  title: "Betterpomodoro",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div className="h-screen px-16 py-32 flex flex-col justify-between items-center mx-auto max-w-7xl">
      <Image
        src={front_img}
        width={622}
        height={560}
        alt="Light bulb image from absurd.design"
        className="z-2"
      />
      <div className="flex flex-col justify-center">
        <div className="text-center mb-32">
          <h1 className="text-3xl md:text-6xl font-extrabold">Deep Focus</h1>
          <p className="text-xl md:text-2xl">
            BetterPomodoro allows you to produce your best work.
          </p>
        </div>
        <Link
          href="/register"
          className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2"
        >
          <Lightbulb className="mr-2 h-4 w-4" /> Continue
        </Link>
      </div>
    </div>
  );
}

export default Page