import { ModeToggle } from "@/components/ModeToggle";
import NavBar from "@/components/NavBar";
import { getUserFromCookie } from "@/lib/auth";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React from "react";
import { db } from "@/lib/db";
import { Lightbulb } from "lucide-react"
export const metadata: Metadata = {
  title: "Revamp Home",
  description: "Generated by create next app",
};
// Note, since themeprovider is in layout.tsx, we wont save theme state between  dashboard and revamp. This will change once everything is gone from dashboard.
const getData = async () => {
    const user = await getUserFromCookie(cookies());
    const projects = await db.project.findMany({
        where: {
        ownerId: user?.id,
        },
        include: {
        tasks: true,
        },
    });

    return { projects };
};

const Page = async () => {
  const user = await getUserFromCookie(cookies());
  return (
    <div className="flex justify-center">
      <div className="h-screen w-screen max-w-2xl p-8 flex flex-col border">
        <div className="flex justify-between">
          <div className="flex">
            <Lightbulb className="w-8 h-8" />
            <h1 className="text-2xl font-bold">BetterPomodoro</h1>
          </div>
        <ModeToggle />
        </div>
        <div>
          <h2>Hello, {user.firstName} 👋 </h2>
        </div>
        
        
        
      </div>
      <NavBar />
      
    </div>
  );
};

export default Page;
