import React from 'react'
export const metadata: Metadata = {
  title: "Revamp Home",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div>page</div>
  )
}

export default Page